export const GET_TRUCKS = "GET_TRUCKS";
export const TRUCKS_RECEIVED = "TRUCKS_RECEIVED";
export const GET_LOCATION = "GET_LOCATION";
export const LOCATION_RECEIVED = "LOCATION_RECEIVED";
export const OPEN_POPOVER = "OPEN_POPOVER";
export const CLOSE_POPOVER = "CLOSE_POPOVER";
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";